### ISSUE TITLE
Does not build on macOS

### ISSUE THREAD

**Issue by wagnerst** [microsoft/pict#89] opened 2022-04-25 08:04 UTC
I had to remove the flag "-werror" in the CMakeLists.txt otherwise it stopped building because of errors.

**Comment by jaccz** [comment] 2022-04-25 15:25
@wagnerst, cmake configs are new to this codebase and it would be great to troubleshoot this a bit more. Is this cmake-version dependent? I assume @bhardwajs (who introduced these configs recently) didn't see it in their environment.

I'll dust off my Mac to see what's going on but it will be a slow process. We can consider removing this flag from the config to unblock the compilation on MacOS until we understand it better.

**Comment by bhardwajs** [comment] 2022-05-03 03:34
@wagnerst - The PR that introduced this change (#85) has a PR build on MacOS: https://pipelines.actions.githubusercontent.com/UYdpZu1K2Abbco3Gy7dEALkh0aw6QbWDK3pBQmV4Okx7ENc2Ng/_apis/pipelines/1/runs/381/signedlogcontent/3?urlExpires=2022-05-03T03%3A30%3A09.0046715Z&urlSigningMethod=HMACV1&urlSignature=AOgmhzVgg4uFpytZqIKdXtJ6y0RAeMPwYlmdjF0qH4k%3D
This build succeeded. So, I am wondering if there is something specific about the configuration you are using. Can you please share more details about the error and the setup of your build machine?

As @jaccz mentioned, I don't have a MacOS to test. And, I agree if understanding and resolving the issue is going to take time, removing this flag from MacOS config is a workaround.

**Comment by wagnerst** [comment] 2022-05-04 10:46
So this is the error I get:

> [ 52%] Building CXX object cli/CMakeFiles/pict_cli.dir/mparser.cpp.o
> /Users/wagnerst/Stuff/ASTA 2022/pict/cli/mparser.cpp:369:20: error: if statement has empty body [-Werror,-Wempty-body]
>         if (found) ;
>                    ^
> /Users/wagnerst/Stuff/ASTA 2022/pict/cli/mparser.cpp:369:20: note: put the semicolon on a separate line to silence this warning
> 1 error generated.
> make[2]: *** [cli/CMakeFiles/pict_cli.dir/mparser.cpp.o] Error 1
> make[1]: *** [cli/CMakeFiles/pict_cli.dir/all] Error 2
> make: *** [all] Error 2

After running cmake --build build

I have installed the CMake using homebrew. 
cmake has the version 3.23.1.
clang is Apple clang version 13.1.6 (clang-1316.0.21.2.3).

Anything else that can be helpful?

**Comment by jaccz** [comment] 2022-05-05 22:21
Tracked it down. Here's the fix. https://github.com/microsoft/pict/pull/91
Silly but it seems to work. If you have a better idea on how this warning can be suppressed, let me know. Whatever the method, it needs to work on all supported compilers and platforms. Yuck.

**Closed** 2022-05-06 15:05 UTC
